# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a94ea2dd0f3c24a3b1bd0bb63048689b08982ed1f6d1aaef0e004045fdf5019fa92e391416323361623227c1ef4051ef9c44ad1bbd23976c14e0c26ea96105b

test:
  secret_key_base: 5c84b90fa7fe776f8326226fcc960b9a4e1a34fee2e1c065100598adb7713cc8d449b07ecb5d7d6084976e1a42cf7115c6ee0bf950e7936d8cd7b29123aefd19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
